# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.17.3

# Mod Properties
mod_version = 0.2.2
maven_group = org.btwr.self_sustainable
archives_base_name = self_sustainable

# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.116.7+1.21.1
btwr_sl_version=0.6.5
btwr_core_version=0.33.2
tough_environment_version=0.13.1
vegehenna_version=0.5
granular_hunger_version=0.5
bwt_version=2.0.1
cloth_config_version=15.0.140
mod_menu_version=11.0.2
emi_version=1.1.12+1.21

# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G